# Generated by Django 3.0.6 on 2020-06-03 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sulbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=30, verbose_name='작성자')),
                ('subject', models.CharField(max_length=50, verbose_name='설비 명칭')),
                ('action', models.CharField(max_length=50, verbose_name='조치 내용')),
                ('date', models.DateField(verbose_name='조치 일자')),
                ('file', models.FileField(upload_to='sulbis/%Y/%m/%d')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sulbis', to=settings.AUTH_USER_MODEL, verbose_name='담당 부서')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
