# Generated by Django 3.0.6 on 2020-06-06 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sulbigram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sulbi',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sulbi',
            name='writer',
        ),
        migrations.AddField(
            model_name='sulbi',
            name='close',
            field=models.DateField(null=True, verbose_name='완료일자'),
        ),
        migrations.AddField(
            model_name='sulbi',
            name='department',
            field=models.CharField(max_length=30, null=True, verbose_name='담당부서'),
        ),
        migrations.AddField(
            model_name='sulbi',
            name='remark',
            field=models.CharField(max_length=100, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='sulbi',
            name='start',
            field=models.DateField(null=True, verbose_name='시작일자'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='action',
            field=models.CharField(max_length=100, null=True, verbose_name='관리사항'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sulbis', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='file',
            field=models.FileField(default='sulbis/SMK.xlsx', null=True, upload_to='sulbis/%Y/%m/%d', verbose_name='관리문서'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='subject',
            field=models.CharField(max_length=50, null=True, verbose_name='설비명칭'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='text',
            field=models.TextField(null=True, verbose_name='관리내역'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일자'),
        ),
    ]
