# Generated by Django 3.0.6 on 2020-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulbigram', '0002_auto_20200606_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ssulbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, null=True, verbose_name='작성자')),
                ('department', models.CharField(max_length=30, null=True, verbose_name='담당부서')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='설비명칭')),
                ('action', models.CharField(max_length=100, null=True, verbose_name='관리사항')),
                ('start', models.DateField(null=True, verbose_name='시작일자')),
                ('close', models.DateField(null=True, verbose_name='완료일자')),
                ('text', models.TextField(null=True, verbose_name='관리내역')),
                ('file', models.FileField(default='sulbis/SMK.xlsx', null=True, upload_to='sulbis/%Y/%m/%d', verbose_name='관리문서')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
