# Generated by Django 3.0.6 on 2020-06-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('sulbigram', '0003_ssulbi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssulbi',
            name='group',
            field=models.CharField(max_length=30, null=True, verbose_name='아파트명'),
        ),
        migrations.AddField(
            model_name='sulbi',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_sulbis', to='auth.Group', verbose_name='아파트명'),
            preserve_default=False,
        ),
    ]
