# Generated by Django 3.0.6 on 2020-06-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulbigram', '0004_auto_20200615_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssulbi',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='설비명칭'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='text',
            field=models.TextField(max_length=500, null=True, verbose_name='관리내역'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='설비명칭'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='text',
            field=models.TextField(max_length=500, null=True, verbose_name='관리내역'),
        ),
    ]
