# Generated by Django 3.0.6 on 2020-06-29 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sulbigram', '0006_auto_20200628_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssulbi',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 5, 25, 43, 805431, tzinfo=utc), null=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 5, 25, 43, 805431, tzinfo=utc), null=True, verbose_name='수정일자'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='close',
            field=models.DateField(default='2020-06-29', null=True, verbose_name='완료일자'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='start',
            field=models.DateField(default='2020-06-29', null=True, verbose_name='시작일자'),
        ),
    ]
