# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sulbigram', '0007_auto_20200629_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssulbi',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='설비번호'),
        ),
        migrations.AddField(
            model_name='ssulbi',
            name='cycle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리주기'),
        ),
        migrations.AddField(
            model_name='sulbi',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='설비번호'),
        ),
        migrations.AddField(
            model_name='sulbi',
            name='cycle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리주기'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 2, 42, 39, 855328, tzinfo=utc), null=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 2, 42, 39, 855328, tzinfo=utc), null=True, verbose_name='수정일자'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리사항'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='close',
            field=models.DateField(default='2020-06-30', null=True, verbose_name='완료일자'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='file',
            field=models.FileField(blank=True, default='sulbis/SMK.xlsx', null=True, upload_to='sulbis/%Y/%m/%d', verbose_name='관리문서'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='start',
            field=models.DateField(default='2020-06-30', null=True, verbose_name='시작일자'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='설비명칭'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='관리내역'),
        ),
    ]
