# Generated by Django 3.0.6 on 2020-06-30 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sulbigram', '0009_auto_20200630_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssulbi',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 7, 2, 17, 3129, tzinfo=utc), null=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 7, 2, 17, 3129, tzinfo=utc), null=True, verbose_name='수정일자'),
        ),
    ]
