# Generated by Django 3.0.6 on 2020-09-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulbigram', '0011_auto_20200630_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssulbi',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='설치장소'),
        ),
    ]
