# Generated by Django 3.0.6 on 2020-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sulbigram', '0012_ssulbi_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='sulbi',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='설치장소'),
        ),
        migrations.AlterField(
            model_name='ssulbi',
            name='remark',
            field=models.CharField(max_length=100, null=True, verbose_name='결재'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='file',
            field=models.FileField(blank=True, default='sulbis/aptgram.xlsx', null=True, upload_to='sulbis/%Y/%m/%d', verbose_name='관리문서'),
        ),
        migrations.AlterField(
            model_name='sulbi',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='결재'),
        ),
    ]
