# Generated by Django 3.0.6 on 2020-06-26 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='작성자')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='소유자')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='양식제목')),
                ('file', models.FileField(default='papers/SMK.xlsx', null=True, upload_to='papers/%Y/%m/%d', verbose_name='문서양식')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='양식설명')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='양식제목')),
                ('file', models.FileField(default='papers/SMK.xlsx', null=True, upload_to='papers/%Y/%m/%d', verbose_name='문서양식')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='양식설명')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_papers', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_papers', to='auth.Group', verbose_name='소유자')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
