# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('papergram', '0002_auto_20200629_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='양식설명'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, default='papers/SMK.xlsx', null=True, upload_to='papers/%Y/%m/%d', verbose_name='문서양식'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='양식제목'),
        ),
        migrations.AlterField(
            model_name='spaper',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 903176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spaper',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 903176, tzinfo=utc)),
        ),
    ]
