# Generated by Django 3.0.6 on 2020-06-30 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('papergram', '0004_auto_20200630_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaper',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 7, 2, 17, 57981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spaper',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 7, 2, 17, 57981, tzinfo=utc)),
        ),
    ]
