# Generated by Django 3.0.6 on 2020-11-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kospipredict',
            name='date',
            field=models.DateTimeField(max_length=10, unique=True, verbose_name='날짜'),
        ),
    ]
