# Generated by Django 3.0.6 on 2020-11-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nameapp', '0002_auto_20201110_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kospipredict',
            name='date',
            field=models.DateField(max_length=10, unique=True, verbose_name='날짜'),
        ),
    ]
