# Generated by Django 3.0.6 on 2020-06-08 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(max_length=10, verbose_name='동')),
                ('ho', models.CharField(max_length=10, verbose_name='호')),
                ('represent', models.CharField(max_length=20, null=True, verbose_name='세대주')),
                ('family', models.CharField(max_length=100, null=True, verbose_name='가족정보')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='대표전화')),
                ('car', models.CharField(max_length=100, null=True, verbose_name='자동차')),
                ('date', models.DateField(null=True, verbose_name='입주일자')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='비고')),
                ('file', models.FileField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='첨부자료')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
