# Generated by Django 3.0.6 on 2020-06-20 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='작성자')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='아파트명')),
                ('contact', models.CharField(max_length=100, verbose_name='신청인')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='민원제기일자')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='민원제목')),
                ('task_1', models.TextField(max_length=500, null=True, verbose_name='민원내역')),
                ('photo_1', models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='민원사진')),
                ('charge', models.CharField(max_length=100, null=True, verbose_name='처리담당')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='응답&처리일자')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='처리부서')),
                ('task_2', models.TextField(max_length=500, null=True, verbose_name='처리내역')),
                ('photo_2', models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='처리사진')),
                ('response', models.CharField(default='처리결과에 대한 평가', max_length=200, verbose_name='민원평가')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='신청인의 주소, 연락처 기재', max_length=100, verbose_name='신청인')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='민원제기일자')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='민원제목')),
                ('task_1', models.TextField(max_length=500, null=True, verbose_name='민원내역')),
                ('photo_1', models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='민원사진')),
                ('charge', models.CharField(max_length=100, null=True, verbose_name='처리담당')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='응답&처리일자')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='처리부서')),
                ('task_2', models.TextField(max_length=500, null=True, verbose_name='처리내역')),
                ('photo_2', models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='처리사진')),
                ('response', models.CharField(default='처리결과에 대한 평가', max_length=200, verbose_name='민원평가')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lives', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_lives', to='auth.Group', verbose_name='아파트명')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
