# Generated by Django 3.0.6 on 2020-07-06 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='작성자')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='아파트명')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='호')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='동')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='민원제기일자')),
                ('subject', models.CharField(max_length=100, null=True, verbose_name='민원제목')),
                ('task_1', models.TextField(max_length=500, null=True, verbose_name='민원내역')),
                ('photo_1', models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='민원사진')),
                ('department', models.CharField(max_length=100, null=True, verbose_name='처리부서')),
                ('charge', models.CharField(max_length=100, null=True, verbose_name='처리담당')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='처리기한')),
                ('close', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='완료일자')),
                ('task_2', models.TextField(max_length=500, null=True, verbose_name='처리내역')),
                ('photo_2', models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='처리사진')),
                ('response', models.CharField(blank=True, max_length=200, null=True, verbose_name='평가:결재')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='민원제기일자')),
                ('subject', models.CharField(default='필수', max_length=100, verbose_name='민원제목')),
                ('task_1', models.TextField(blank=True, max_length=500, null=True, verbose_name='민원내역')),
                ('photo_1', models.ImageField(blank=True, default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='민원사진')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='담당부서')),
                ('charge', models.CharField(blank=True, max_length=100, null=True, verbose_name='처리담당')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='처리기한')),
                ('close', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='처리완료')),
                ('task_2', models.TextField(blank=True, max_length=500, null=True, verbose_name='처리내역')),
                ('photo_2', models.ImageField(blank=True, default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='처리사진')),
                ('response', models.CharField(blank=True, max_length=200, null=True, verbose_name='평가:결재')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lives', to=settings.AUTH_USER_MODEL)),
                ('first_name', models.ForeignKey(blank=True, db_column='first_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_lives', to=settings.AUTH_USER_MODEL, verbose_name='호')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_lives', to='auth.Group', verbose_name='아파트명')),
                ('last_name', models.ForeignKey(blank=True, db_column='last_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_lives', to=settings.AUTH_USER_MODEL, verbose_name='동')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
