# Generated by Django 3.0.6 on 2020-06-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='life',
            name='car',
        ),
        migrations.RemoveField(
            model_name='life',
            name='date',
        ),
        migrations.RemoveField(
            model_name='life',
            name='dong',
        ),
        migrations.RemoveField(
            model_name='life',
            name='family',
        ),
        migrations.RemoveField(
            model_name='life',
            name='file',
        ),
        migrations.RemoveField(
            model_name='life',
            name='ho',
        ),
        migrations.RemoveField(
            model_name='life',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='life',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='life',
            name='represent',
        ),
        migrations.AddField(
            model_name='life',
            name='charge',
            field=models.CharField(max_length=50, null=True, verbose_name='처리담당'),
        ),
        migrations.AddField(
            model_name='life',
            name='contact',
            field=models.CharField(default='신청인의 주소와 연락처 기재란', max_length=10, verbose_name='신청인'),
        ),
        migrations.AddField(
            model_name='life',
            name='department',
            field=models.CharField(max_length=50, null=True, verbose_name='처리부서'),
        ),
        migrations.AddField(
            model_name='life',
            name='photo_1',
            field=models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='민원사진'),
        ),
        migrations.AddField(
            model_name='life',
            name='photo_2',
            field=models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='처리사진'),
        ),
        migrations.AddField(
            model_name='life',
            name='response',
            field=models.CharField(default='처리결과에 대한 평가', max_length=200, verbose_name='민원평가'),
        ),
        migrations.AddField(
            model_name='life',
            name='subject',
            field=models.CharField(max_length=50, null=True, verbose_name='민원제목'),
        ),
        migrations.AddField(
            model_name='life',
            name='task_1',
            field=models.TextField(max_length=500, null=True, verbose_name='민원내역'),
        ),
        migrations.AddField(
            model_name='life',
            name='task_2',
            field=models.TextField(max_length=500, null=True, verbose_name='처리내역'),
        ),
        migrations.AlterField(
            model_name='life',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='민원제기일자'),
        ),
        migrations.AlterField(
            model_name='life',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='응답&처리일자'),
        ),
    ]
