# Generated by Django 3.0.6 on 2020-06-29 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slife',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 836324, tzinfo=utc), verbose_name='민원제기일자'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 836324, tzinfo=utc), verbose_name='응답&처리일자'),
        ),
    ]
