# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0002_auto_20200629_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='life',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='slife',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='life',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='slife',
            name='updated',
        ),
        migrations.AddField(
            model_name='life',
            name='close',
            field=models.DateField(blank=True, default='2020-06-30', verbose_name='처리완료'),
        ),
        migrations.AddField(
            model_name='life',
            name='date',
            field=models.DateField(blank=True, default='2020-06-30', verbose_name='처리기한'),
        ),
        migrations.AddField(
            model_name='slife',
            name='close',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 888212, tzinfo=utc), verbose_name='완료일자'),
        ),
        migrations.AddField(
            model_name='slife',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 888212, tzinfo=utc), verbose_name='처리기한'),
        ),
        migrations.AlterField(
            model_name='life',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='처리담당'),
        ),
        migrations.AlterField(
            model_name='life',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='처리부서'),
        ),
        migrations.AlterField(
            model_name='life',
            name='photo_1',
            field=models.ImageField(blank=True, default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='민원사진'),
        ),
        migrations.AlterField(
            model_name='life',
            name='photo_2',
            field=models.ImageField(blank=True, default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='처리사진'),
        ),
        migrations.AlterField(
            model_name='life',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='평가:결재'),
        ),
        migrations.AlterField(
            model_name='life',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='민원제목'),
        ),
        migrations.AlterField(
            model_name='life',
            name='task_1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='민원내역'),
        ),
        migrations.AlterField(
            model_name='life',
            name='task_2',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='처리내역'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 888212, tzinfo=utc), verbose_name='민원제기일자'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='평가:결재'),
        ),
    ]
