# Generated by Django 3.0.6 on 2020-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0002_auto_20200707_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='open',
            field=models.CharField(blank=True, default='비공개', max_length=200, null=True, verbose_name='비공개:공개'),
        ),
        migrations.AddField(
            model_name='life',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='결재'),
        ),
        migrations.AddField(
            model_name='slife',
            name='open',
            field=models.CharField(blank=True, default='비공개', max_length=200, null=True, verbose_name='비공개:공개'),
        ),
        migrations.AddField(
            model_name='slife',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='결재'),
        ),
    ]
