# Generated by Django 3.0.6 on 2020-06-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0002_auto_20200610_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='작성자')),
                ('contact', models.CharField(max_length=50, verbose_name='신청인')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='민원제기일자')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='민원제목')),
                ('task_1', models.TextField(max_length=500, null=True, verbose_name='민원내역')),
                ('photo_1', models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='민원사진')),
                ('charge', models.CharField(max_length=50, null=True, verbose_name='처리담당')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='응답&처리일자')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='처리부서')),
                ('task_2', models.TextField(max_length=500, null=True, verbose_name='처리내역')),
                ('photo_2', models.ImageField(default='lives/aptgram.jpg', null=True, upload_to='lives/%Y/%m/%d', verbose_name='처리사진')),
                ('response', models.CharField(default='처리결과에 대한 평가', max_length=200, verbose_name='민원평가')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AlterField(
            model_name='life',
            name='contact',
            field=models.CharField(default='신청인의 주소, 연락처 기재', max_length=50, verbose_name='신청인'),
        ),
    ]
