# Generated by Django 3.0.6 on 2020-06-30 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0003_auto_20200630_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='close',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 6, 46, 24, 207212, tzinfo=utc), verbose_name='완료일자'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 6, 46, 24, 207212, tzinfo=utc), verbose_name='민원제기일자'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 30, 6, 46, 24, 207212, tzinfo=utc), verbose_name='처리기한'),
        ),
    ]
