# Generated by Django 3.0.6 on 2020-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0003_auto_20200911_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='progress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='진행상황'),
        ),
        migrations.AddField(
            model_name='slife',
            name='progress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='진행상황'),
        ),
        migrations.AlterField(
            model_name='life',
            name='applicant',
            field=models.CharField(max_length=100, null=True, verbose_name='신청인(성명:동-호:전화번호)'),
        ),
        migrations.AlterField(
            model_name='life',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주민후기'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='applicant',
            field=models.CharField(max_length=100, null=True, verbose_name='신청인(성명:동-호:전화번호)'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='주민후기'),
        ),
    ]
