# Generated by Django 3.0.6 on 2020-06-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('lifegram', '0003_auto_20200612_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='life',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_lives', to='auth.Group', verbose_name='아파트명'),
        ),
        migrations.AddField(
            model_name='slife',
            name='group',
            field=models.CharField(max_length=50, null=True, verbose_name='아파트명'),
        ),
    ]
