# Generated by Django 3.0.6 on 2020-06-30 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0004_auto_20200630_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slife',
            name='close',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 7, 2, 17, 40029, tzinfo=utc), verbose_name='완료일자'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 7, 2, 17, 39033, tzinfo=utc), verbose_name='민원제기일자'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 30, 7, 2, 17, 40029, tzinfo=utc), verbose_name='처리기한'),
        ),
    ]
