# Generated by Django 3.0.6 on 2020-06-30 07:28

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lifegram', '0005_auto_20200630_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life',
            name='close',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='처리완료'),
        ),
        migrations.AlterField(
            model_name='life',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='처리기한'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='close',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='완료일자'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 7, 28, 1, 143417, tzinfo=utc), verbose_name='민원제기일자'),
        ),
        migrations.AlterField(
            model_name='slife',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='처리기한'),
        ),
    ]
