# Generated by Django 3.0.6 on 2020-05-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0002_auto_20200525_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='photo',
        ),
    ]
