# Generated by Django 3.0.6 on 2020-05-26 02:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filegram', '0003_remove_file_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='File_tb',
        ),
    ]
