# Generated by Django 3.0.6 on 2020-06-03 01:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filegram', '0004_auto_20200526_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_tb',
            new_name='File',
        ),
    ]
