# Generated by Django 3.0.6 on 2020-06-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0006_auto_20200606_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, null=True, verbose_name='작성자')),
                ('department', models.CharField(max_length=20, null=True, verbose_name='부서')),
                ('charge', models.CharField(max_length=50, null=True, verbose_name='담당자')),
                ('manager', models.CharField(default='확인 요망', max_length=50, verbose_name='관리자')),
                ('director', models.CharField(default='확인 요망', max_length=50, verbose_name='승인역')),
                ('super', models.CharField(default='확인 요망', max_length=50, verbose_name='추인역')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='안건제목')),
                ('abstract', models.TextField(default='요약', max_length=500, verbose_name='안건요약')),
                ('file', models.FileField(default='files/aptgram.jpg', null=True, upload_to='files/%Y/%m/%d', verbose_name='품의문서')),
                ('remark', models.CharField(default='없음', max_length=100, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AlterField(
            model_name='file',
            name='abstract',
            field=models.TextField(default='요약', max_length=500, verbose_name='안건요약'),
        ),
        migrations.AlterField(
            model_name='file',
            name='charge',
            field=models.CharField(max_length=50, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='director',
            field=models.CharField(default='확인 요망', max_length=50, verbose_name='승인역'),
        ),
        migrations.AlterField(
            model_name='file',
            name='manager',
            field=models.CharField(default='확인 요망', max_length=50, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(default='없음', max_length=100, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='file',
            name='super',
            field=models.CharField(default='확인 요망', max_length=50, verbose_name='추인역'),
        ),
    ]
