# Generated by Django 3.0.6 on 2020-06-15 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filegram', '0007_auto_20200612_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_files', to='auth.Group', verbose_name='아파트명'),
        ),
        migrations.AddField(
            model_name='sfile',
            name='group',
            field=models.CharField(max_length=20, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='department',
            field=models.CharField(max_length=20, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일자'),
        ),
    ]
