# Generated by Django 3.0.6 on 2020-06-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0008_auto_20200615_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='file',
            name='director',
            field=models.CharField(default='확인 요망', max_length=100, verbose_name='승인역'),
        ),
        migrations.AlterField(
            model_name='file',
            name='manager',
            field=models.CharField(default='확인 요망', max_length=100, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='안건제목'),
        ),
        migrations.AlterField(
            model_name='file',
            name='super',
            field=models.CharField(default='확인 요망', max_length=100, verbose_name='추인역'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='director',
            field=models.CharField(default='확인 요망', max_length=100, verbose_name='승인역'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='manager',
            field=models.CharField(default='확인 요망', max_length=100, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='안건제목'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='super',
            field=models.CharField(default='확인 요망', max_length=100, verbose_name='추인역'),
        ),
    ]
