# Generated by Django 3.0.6 on 2020-06-29 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0009_auto_20200620_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfile',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 787454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 787454, tzinfo=utc)),
        ),
    ]
