# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0010_auto_20200629_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='abstract',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='안건요약'),
        ),
        migrations.AlterField(
            model_name='file',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='file',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리소장'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, default='files/aptgram.jpg', null=True, upload_to='files/%Y/%m/%d', verbose_name='품의문서'),
        ),
        migrations.AlterField(
            model_name='file',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='file',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='안건제목'),
        ),
        migrations.AlterField(
            model_name='file',
            name='super',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='입주자대표회장'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='abstract',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='안건요약'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 840342, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리소장'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='file',
            field=models.FileField(blank=True, default='files/aptgram.jpg', null=True, upload_to='files/%Y/%m/%d', verbose_name='품의문서'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='안건제목'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='super',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='입주자대표회장'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 840342, tzinfo=utc)),
        ),
    ]
