# Generated by Django 3.0.6 on 2020-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0014_auto_20200630_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, default='files/aptgram.xlsx', null=True, upload_to='files/%Y/%m/%d', verbose_name='품의문서'),
        ),
        migrations.AlterField(
            model_name='file',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='결재자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='결재'),
        ),
    ]
