# Generated by Django 3.0.6 on 2020-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0015_auto_20200911_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='sfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sfile',
            name='remark',
        ),
        migrations.AddField(
            model_name='file',
            name='board',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='이사'),
        ),
        migrations.AddField(
            model_name='file',
            name='visor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='회장'),
        ),
        migrations.AddField(
            model_name='sfile',
            name='board',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='이사'),
        ),
        migrations.AddField(
            model_name='sfile',
            name='visor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='회장'),
        ),
        migrations.AlterField(
            model_name='file',
            name='charge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='관리소장'),
        ),
        migrations.AlterField(
            model_name='file',
            name='manager',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='결재자'),
        ),
        migrations.AlterField(
            model_name='file',
            name='super',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='감사'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='charge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='관리소장'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='manager',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='super',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='감사'),
        ),
    ]
