# Generated by Django 3.0.6 on 2020-09-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0016_auto_20200919_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='approval',
            field=models.CharField(default='123456', max_length=100, verbose_name='결재자 이름 및 직위'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sfile',
            name='approval',
            field=models.CharField(default=1, max_length=100, verbose_name='결재자 이름 및 직위'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='이사비번'),
        ),
        migrations.AlterField(
            model_name='file',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='반장비번'),
        ),
        migrations.AlterField(
            model_name='file',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소장비번'),
        ),
        migrations.AlterField(
            model_name='file',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자비번'),
        ),
        migrations.AlterField(
            model_name='file',
            name='super',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='감사비번'),
        ),
        migrations.AlterField(
            model_name='file',
            name='visor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='회장비번'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='board',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='이사비번'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='반장비번'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소장비번'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자비번'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='super',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='감사비번'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='visor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='회장비번'),
        ),
    ]
