# Generated by Django 3.0.6 on 2020-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filegram', '0017_auto_20200921_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='approval',
            field=models.CharField(max_length=100, verbose_name='결재자(부서:직위:이름)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='과장비번'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='approval',
            field=models.CharField(max_length=100, verbose_name='결재자(부서:직위:이름)'),
        ),
        migrations.AlterField(
            model_name='sfile',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='과장비번'),
        ),
    ]
