# Generated by Django 3.0.6 on 2020-05-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(max_length=10)),
                ('ho', models.CharField(max_length=10)),
                ('represent', models.CharField(max_length=20)),
                ('family', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('car', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
