# Generated by Django 3.0.6 on 2020-06-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='represent',
            field=models.CharField(max_length=100, verbose_name='입주민'),
        ),
    ]
