# Generated by Django 3.0.6 on 2020-06-04 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='장치 명칭')),
                ('location', models.CharField(max_length=50, verbose_name='보관 장소')),
                ('manager_1', models.CharField(max_length=30, verbose_name='관리자(정)')),
                ('manager_2', models.CharField(max_length=30, verbose_name='관리자(부)')),
                ('spec', models.CharField(max_length=100, verbose_name='규격')),
                ('date', models.DateField(verbose_name='구입 일자')),
                ('photo', models.ImageField(default=None, upload_to='equips/%Y/%m/%d')),
                ('remark', models.CharField(max_length=200, verbose_name='비고')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_equips', to=settings.AUTH_USER_MODEL, verbose_name='담당 부서')),
            ],
            options={
                'ordering': ['-author'],
            },
        ),
    ]
