# Generated by Django 3.0.6 on 2020-06-06 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipgram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='관리부서'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_equips', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='date',
            field=models.DateField(blank=True, verbose_name='구입일자'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='location',
            field=models.CharField(blank=True, max_length=50, verbose_name='보관장소'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='manager_1',
            field=models.CharField(blank=True, max_length=30, verbose_name='관리자(정)'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='manager_2',
            field=models.CharField(blank=True, max_length=30, verbose_name='관리자(부)'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='photo',
            field=models.ImageField(default='equips/aptgram.jpg', upload_to='equips/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='장치명칭'),
        ),
    ]
