# Generated by Django 3.0.6 on 2020-06-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0002_auto_20200606_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='관리부서'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='보관장소'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='manager_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='관리자(정)'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='manager_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='관리자(부)'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='장치명칭'),
        ),
    ]
