# Generated by Django 3.0.6 on 2020-06-15 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipgram', '0004_sequip'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_equips', to='auth.Group', verbose_name='아파트명'),
        ),
        migrations.AddField(
            model_name='sequip',
            name='group',
            field=models.CharField(blank=True, max_length=100, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_equips', to=settings.AUTH_USER_MODEL, verbose_name='그룹'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='작성자'),
        ),
    ]
