# Generated by Django 3.0.6 on 2020-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0006_auto_20200620_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='date',
            field=models.DateField(blank=True, default='2020-06-28', verbose_name='구입일자'),
        ),
    ]
