# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0008_auto_20200629_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비품번호'),
        ),
        migrations.AddField(
            model_name='sequip',
            name='code',
            field=models.CharField(default=1, max_length=100, verbose_name='비품번호'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equip',
            name='date',
            field=models.DateField(blank=True, default='2020-06-30', verbose_name='구입일자'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리부서'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='보관장소'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='manager_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자(정)'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='manager_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자(부)'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='규격'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='비품명칭'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 876246, tzinfo=utc), verbose_name='구입일자'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='비품명칭'),
        ),
    ]
