# Generated by Django 3.0.6 on 2020-06-30 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0009_auto_20200630_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='photo',
            field=models.ImageField(blank=True, default='equips/aptgram.jpg', null=True, upload_to='equips/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비품명칭'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비품번호'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 30, 6, 6, 22, 542819, tzinfo=utc), null=True, verbose_name='구입일자'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리부서'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='보관장소'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='manager_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자(정)'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='manager_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자(부)'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='photo',
            field=models.ImageField(blank=True, default='equips/aptgram.jpg', null=True, upload_to='equips/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='spec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='규격'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비품명칭'),
        ),
    ]
