# Generated by Django 3.0.6 on 2020-06-30 06:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0010_auto_20200630_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequip',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 30, 6, 49, 0, 925192, tzinfo=utc), null=True, verbose_name='구입일자'),
        ),
    ]
