# Generated by Django 3.0.6 on 2020-06-30 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0012_auto_20200630_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='구입일자'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='구입일자'),
        ),
    ]
