# Generated by Django 3.0.6 on 2020-09-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0013_auto_20200630_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip',
            name='file',
            field=models.FileField(default='sulbis/SMK.xlsx', null=True, upload_to='sulbis/%Y/%m/%d', verbose_name='관리이력'),
        ),
        migrations.AddField(
            model_name='equip',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비품수량'),
        ),
        migrations.AddField(
            model_name='equip',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='사용내역'),
        ),
    ]
