# Generated by Django 3.0.6 on 2020-09-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0014_auto_20200908_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='sequip',
            name='photo',
        ),
        migrations.AddField(
            model_name='sequip',
            name='file',
            field=models.FileField(blank=True, default='equips/SMK.xlsx', null=True, upload_to='equips/%Y/%m/%d', verbose_name='관리이력'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='file',
            field=models.FileField(blank=True, default='equips/SMK.xlsx', null=True, upload_to='equips/%Y/%m/%d', verbose_name='관리이력'),
        ),
    ]
