# Generated by Django 3.0.6 on 2020-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipgram', '0015_auto_20200908_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequip',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비품수량'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='file',
            field=models.FileField(blank=True, default='equips/aptgram.xlsx', null=True, upload_to='equips/%Y/%m/%d', verbose_name='관리이력'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='결재'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='결재'),
        ),
    ]
