# Generated by Django 3.0.6 on 2020-12-10 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('equipgram', '0016_auto_20200911_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_equips', to='auth.Group', verbose_name='사용목적'),
        ),
        migrations.AlterField(
            model_name='sequip',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='사용목적'),
        ),
    ]
