# Generated by Django 3.0.6 on 2020-08-27 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='작성자')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='아파트명')),
                ('dong', models.CharField(max_length=100, null=True, verbose_name='동')),
                ('ho', models.CharField(max_length=100, null=True, verbose_name='호')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='공고일자')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='세대주')),
                ('text', models.TextField(blank=True, max_length=300, null=True, verbose_name='전체 알림')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(max_length=100, verbose_name='동')),
                ('ho', models.CharField(max_length=100, verbose_name='호')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='공고일자')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='공고제목')),
                ('text', models.TextField(blank=True, max_length=300, null=True, verbose_name='공고내용')),
                ('photo', models.ImageField(blank=True, default='news/aptgram.jpg', null=True, upload_to='news/%Y/%m/%d', verbose_name='공고사진')),
                ('file', models.FileField(blank=True, default='news/SMK.xlsx', null=True, upload_to='news/%Y/%m/%d', verbose_name='공고파일')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_news', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_news', to='auth.Group', verbose_name='아파트명')),
            ],
            options={
                'ordering': ['-date', '-updated'],
            },
        ),
    ]
