# Generated by Django 3.0.6 on 2020-09-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsgram', '0002_auto_20200908_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
    ]
