# Generated by Django 3.0.6 on 2020-09-11 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsgram', '0003_remove_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='remark',
            field=models.CharField(blank=True, default='결재', max_length=100, null=True, verbose_name='결재'),
        ),
        migrations.AddField(
            model_name='snews',
            name='remark',
            field=models.CharField(blank=True, default='기안', max_length=100, null=True, verbose_name='기안:승인'),
        ),
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, default='news/aptgram.xlsx', null=True, upload_to='news/%Y/%m/%d', verbose_name='공고파일'),
        ),
        migrations.AlterField(
            model_name='snews',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='snews',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='결재일'),
        ),
    ]
