# Generated by Django 3.0.6 on 2020-06-06 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(null=True, verbose_name='시작일자')),
                ('close', models.DateField(null=True, verbose_name='완료일자')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='담당부서')),
                ('charge', models.CharField(max_length=50, null=True, verbose_name='담당자')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='업무제목')),
                ('task', models.TextField(max_length=500, null=True, verbose_name='업무내역')),
                ('photo', models.ImageField(default='plans/aptgram.jpg', null=True, upload_to='plans/%Y/%m/%d', verbose_name='참고사진')),
                ('manager', models.CharField(max_length=50, null=True, verbose_name='업무관리')),
                ('director', models.CharField(max_length=50, null=True, verbose_name='책임관리')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
