# Generated by Django 3.0.6 on 2020-06-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plangram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='작성자')),
                ('start', models.DateField(null=True, verbose_name='시작일자')),
                ('close', models.DateField(null=True, verbose_name='완료일자')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='담당부서')),
                ('charge', models.CharField(max_length=50, null=True, verbose_name='담당자')),
                ('subject', models.CharField(max_length=50, null=True, verbose_name='업무제목')),
                ('task', models.TextField(max_length=500, null=True, verbose_name='업무내역')),
                ('photo', models.ImageField(default='plans/aptgram.jpg', null=True, upload_to='plans/%Y/%m/%d', verbose_name='참고사진')),
                ('manager', models.CharField(max_length=50, null=True, verbose_name='업무관리')),
                ('director', models.CharField(max_length=50, null=True, verbose_name='책임관리')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
