# Generated by Django 3.0.6 on 2020-06-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('plangram', '0002_splan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_plans', to='auth.Group', verbose_name='아파트명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='splan',
            name='group',
            field=models.CharField(max_length=50, null=True, verbose_name='아파트명'),
        ),
    ]
