# Generated by Django 3.0.6 on 2020-06-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plangram', '0003_auto_20200615_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='책임관리'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='manager',
            field=models.CharField(max_length=100, null=True, verbose_name='업무관리'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='업무제목'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='책임관리'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='manager',
            field=models.CharField(max_length=100, null=True, verbose_name='업무관리'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='업무제목'),
        ),
    ]
