# Generated by Django 3.0.6 on 2020-06-29 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plangram', '0005_auto_20200628_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='close',
            field=models.DateField(default='2020-06-29', null=True, verbose_name='완료일자'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start',
            field=models.DateField(default='2020-06-29', null=True, verbose_name='시작일자'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 829338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='splan',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 829338, tzinfo=utc)),
        ),
    ]
