# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plangram', '0006_auto_20200629_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='close',
            field=models.DateField(default='2020-06-30', null=True, verbose_name='완료일자'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리소장'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='photo',
            field=models.ImageField(blank=True, default='plans/aptgram.jpg', null=True, upload_to='plans/%Y/%m/%d', verbose_name='참고사진'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start',
            field=models.DateField(default='2020-06-30', null=True, verbose_name='시작일자'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='업무제목'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='task',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='업무내역'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 882257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='splan',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='관리소장'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='manager',
            field=models.CharField(max_length=100, null=True, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 882257, tzinfo=utc)),
        ),
    ]
