# Generated by Django 3.0.6 on 2020-09-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plangram', '0011_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='close',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='director',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='task',
        ),
        migrations.RemoveField(
            model_name='splan',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='splan',
            name='close',
        ),
        migrations.RemoveField(
            model_name='splan',
            name='director',
        ),
        migrations.RemoveField(
            model_name='splan',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='splan',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='splan',
            name='start',
        ),
        migrations.RemoveField(
            model_name='splan',
            name='task',
        ),
        migrations.AddField(
            model_name='plan',
            name='regpsw',
            field=models.CharField(blank=True, default='6자리 숫자 또는 영문자(대, 소)', max_length=100, null=True, verbose_name='등록비번'),
        ),
        migrations.AddField(
            model_name='plan',
            name='usepsw',
            field=models.CharField(blank=True, default='자동생성됩니다.', max_length=100, null=True, verbose_name='사용비번'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='직위/직급'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='직위/직급'),
        ),
    ]
