# Generated by Django 3.0.6 on 2020-09-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plangram', '0012_auto_20200919_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='remark',
            field=models.CharField(default='qqq', max_length=200, verbose_name='용도'),
            preserve_default=False,
        ),
    ]
