# Generated by Django 3.0.6 on 2020-09-19 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plangram', '0013_auto_20200919_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='발급일자'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='splan',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='발급일자'),
        ),
    ]
