# Generated by Django 3.0.6 on 2020-08-12 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='업무', max_length=200, verbose_name='일정')),
                ('description', models.TextField(default='상세내용', max_length=500, verbose_name='상세내용')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작일자')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='종료일자')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_times', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_times', to='auth.Group', verbose_name='아파트명')),
            ],
        ),
    ]
