# Generated by Django 3.0.6 on 2020-08-13 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='종료일자'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='시작일자'),
        ),
    ]
