# Generated by Django 3.0.6 on 2020-08-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timegram', '0002_auto_20200813_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='charge',
            field=models.CharField(default='담당자', max_length=100, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='time',
            name='department',
            field=models.CharField(default='담당부서', max_length=100, verbose_name='담당부서'),
        ),
    ]
