# Generated by Django 3.0.6 on 2020-08-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timegram', '0003_auto_20200821_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='charge',
            field=models.CharField(blank=True, default='비고', max_length=100, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='time',
            name='department',
            field=models.CharField(blank=True, default='담당부서', max_length=100, null=True, verbose_name='담당부서'),
        ),
        migrations.AlterField(
            model_name='time',
            name='description',
            field=models.TextField(blank=True, default='상세내용', max_length=500, null=True, verbose_name='상세내용'),
        ),
    ]
