# Generated by Django 3.0.6 on 2020-08-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timegram', '0004_auto_20200823_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='charge',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='time',
            name='department',
        ),
        migrations.RemoveField(
            model_name='time',
            name='title',
        ),
        migrations.AddField(
            model_name='time',
            name='action',
            field=models.CharField(blank=True, default='저장', max_length=100, null=True, verbose_name='일정편집'),
        ),
        migrations.AddField(
            model_name='time',
            name='subject',
            field=models.CharField(default='업무', max_length=200, verbose_name='업무'),
        ),
    ]
