# Generated by Django 3.0.6 on 2020-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timegram', '0005_auto_20200823_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='appendix',
            field=models.CharField(blank=True, default='추가내용', max_length=100, null=True, verbose_name='추가내용'),
        ),
        migrations.AlterField(
            model_name='time',
            name='description',
            field=models.TextField(blank=True, default='업무내용', max_length=500, null=True, verbose_name='업무내용'),
        ),
        migrations.AlterField(
            model_name='time',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='결재'),
        ),
        migrations.AlterField(
            model_name='time',
            name='subject',
            field=models.CharField(default='업무제목', max_length=200, verbose_name='업무제목'),
        ),
    ]
