# Generated by Django 3.0.6 on 2020-12-10 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('timegram', '0006_auto_20200911_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_times', to='auth.Group', verbose_name='사용목적'),
        ),
        migrations.AlterField(
            model_name='time',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='비고'),
        ),
    ]
