# Generated by Django 3.0.6 on 2020-11-05 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sshrimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='장치번호')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='양식장명')),
                ('department', models.CharField(max_length=100, verbose_name='위치구분')),
                ('subject', models.CharField(max_length=100, verbose_name='장치종류')),
                ('serial', models.CharField(max_length=100, verbose_name='장치번호')),
                ('temp', models.IntegerField(blank=True, default=0, null=True, verbose_name='온도(*C)')),
                ('ph', models.IntegerField(blank=True, default=0, null=True, verbose_name='pH')),
                ('salt', models.IntegerField(blank=True, default=0, null=True, verbose_name='염도(ppm)')),
                ('do', models.IntegerField(blank=True, default=0, null=True, verbose_name='DO(ppm)')),
                ('nh4', models.IntegerField(blank=True, default=0, null=True, verbose_name='암모니아(ppm)')),
                ('turbid', models.IntegerField(blank=True, default=0, null=True, verbose_name='탁도(ppm)')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='조치사항')),
                ('naoh', models.IntegerField(blank=True, default=0, null=True, verbose_name='알칼리(%)')),
                ('dang', models.IntegerField(blank=True, default=0, null=True, verbose_name='당밀(%)')),
                ('blower', models.IntegerField(blank=True, default=0, null=True, verbose_name='블로워(%)')),
                ('security', models.CharField(blank=True, max_length=200, null=True, verbose_name='보안장치')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='특기사항')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='측정일시')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Shrimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='호지구분')),
                ('subject', models.CharField(max_length=100, verbose_name='장치종류')),
                ('serial', models.CharField(max_length=100, verbose_name='장치번호')),
                ('temp', models.IntegerField(blank=True, default=0, null=True, verbose_name='온도(*C)')),
                ('ph', models.IntegerField(blank=True, default=0, null=True, verbose_name='pH')),
                ('salt', models.IntegerField(blank=True, default=0, null=True, verbose_name='염도(ppm)')),
                ('do', models.IntegerField(blank=True, default=0, null=True, verbose_name='DO(ppm)')),
                ('nh4', models.IntegerField(blank=True, default=0, null=True, verbose_name='암모니아(ppm)')),
                ('turbid', models.IntegerField(blank=True, default=0, null=True, verbose_name='탁도(ppm)')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='조치사항')),
                ('naoh', models.IntegerField(blank=True, default=0, null=True, verbose_name='알칼리(%)')),
                ('dang', models.IntegerField(blank=True, default=0, null=True, verbose_name='당밀(%)')),
                ('blower', models.IntegerField(blank=True, default=0, null=True, verbose_name='블로워(%)')),
                ('security', models.CharField(blank=True, max_length=200, null=True, verbose_name='보안장치')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='특기사항')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='측정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shrimps', to=settings.AUTH_USER_MODEL, verbose_name='양식장명')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_shrimps', to='auth.Group', verbose_name='양식종류')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
