# Generated by Django 3.0.6 on 2020-11-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrimpgram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshrimp',
            name='department',
        ),
        migrations.AddField(
            model_name='sshrimp',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='위치구분'),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='호지구분'),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='장치종류'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='장치종류'),
        ),
    ]
