# Generated by Django 3.0.6 on 2020-11-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrimpgram', '0002_auto_20201105_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrimp',
            name='action',
        ),
        migrations.RemoveField(
            model_name='sshrimp',
            name='action',
        ),
        migrations.AddField(
            model_name='shrimp',
            name='boiler',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='보일러'),
        ),
        migrations.AddField(
            model_name='shrimp',
            name='no2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='아질산(ppm)'),
        ),
        migrations.AddField(
            model_name='sshrimp',
            name='boiler',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='보일러'),
        ),
        migrations.AddField(
            model_name='sshrimp',
            name='no2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='아질산(ppm)'),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='blower',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='블로워'),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='일시'),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='dang',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='당밀'),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='naoh',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='알칼리'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='양식장명'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='blower',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='블로워'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='일시'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='dang',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='당밀'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='양식종류'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='호지구분'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='naoh',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='알칼리'),
        ),
    ]
