# Generated by Django 3.0.6 on 2020-11-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrimpgram', '0003_auto_20201107_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimp',
            name='alkali',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='알칼리도'),
        ),
        migrations.AddField(
            model_name='sshrimp',
            name='alkali',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='알칼리도'),
        ),
    ]
