# Generated by Django 3.0.6 on 2020-11-10 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shrimpgram', '0004_auto_20201109_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimp',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='수정일시'),
        ),
        migrations.AddField(
            model_name='sshrimp',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='shrimp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='일시'),
        ),
        migrations.AlterField(
            model_name='sshrimp',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='일시'),
        ),
    ]
