# Generated by Django 3.0.6 on 2020-11-10 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shrimpgram', '0005_auto_20201110_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='shrimp',
            name='xdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='수정일시'),
        ),
        migrations.AddField(
            model_name='sshrimp',
            name='xdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='수정일시'),
        ),
    ]
