# Generated by Django 3.0.6 on 2020-06-12 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Smeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='작성자')),
                ('dong', models.CharField(max_length=50, null=True, verbose_name='동')),
                ('ho', models.CharField(max_length=50, null=True, verbose_name='호')),
                ('utility', models.CharField(default='수도', max_length=50, verbose_name='종류')),
                ('mtr', models.IntegerField(default=0, verbose_name='미터사용량')),
                ('cor', models.IntegerField(default=0, verbose_name='보정사용량')),
                ('amount', models.IntegerField(default=0, verbose_name='요금')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='검침일자')),
                ('action', models.CharField(default='검침', max_length=50, verbose_name='처리현황')),
                ('charge', models.CharField(max_length=20, null=True, verbose_name='검침담당')),
                ('manager', models.CharField(max_length=20, null=True, verbose_name='관리담당')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(max_length=50, null=True, verbose_name='동')),
                ('ho', models.CharField(max_length=50, null=True, verbose_name='호')),
                ('utility', models.CharField(default='수도', max_length=50, verbose_name='종류')),
                ('mtr', models.IntegerField(default=0, verbose_name='미터사용량')),
                ('cor', models.IntegerField(default=0, verbose_name='보정사용량')),
                ('amount', models.IntegerField(default=0, verbose_name='요금')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='검침일자')),
                ('action', models.CharField(default='검침', max_length=50, verbose_name='처리현황')),
                ('charge', models.CharField(max_length=20, null=True, verbose_name='검침담당')),
                ('manager', models.CharField(max_length=20, null=True, verbose_name='관리담당')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
