# Generated by Django 3.0.6 on 2020-06-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metergram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='serial',
            field=models.CharField(max_length=20, null=True, verbose_name='기기번호'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='serial',
            field=models.CharField(max_length=20, null=True, verbose_name='기기번호'),
        ),
    ]
