# Generated by Django 3.0.6 on 2020-06-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metergram', '0002_auto_20200613_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeter',
            name='group',
            field=models.CharField(max_length=50, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='author',
            field=models.CharField(default='원격검침', max_length=50, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='author',
            field=models.CharField(default='원격검침', max_length=50, verbose_name='작성자'),
        ),
    ]
