# Generated by Django 3.0.6 on 2020-06-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('metergram', '0005_meter_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_meters', to='auth.Group', verbose_name='아파트명'),
            preserve_default=False,
        ),
    ]
