# Generated by Django 3.0.6 on 2020-06-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metergram', '0006_meter_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='xauthor',
        ),
    ]
