# Generated by Django 3.0.6 on 2020-06-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metergram', '0007_remove_meter_xauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='action',
            field=models.CharField(default='검침', max_length=100, verbose_name='처리현황'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='검침담당'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='dong',
            field=models.CharField(max_length=100, null=True, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='ho',
            field=models.CharField(max_length=100, null=True, verbose_name='호'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='manager',
            field=models.CharField(max_length=100, null=True, verbose_name='관리담당'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='serial',
            field=models.CharField(max_length=100, null=True, verbose_name='기기번호'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='utility',
            field=models.CharField(default='수도', max_length=100, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='action',
            field=models.CharField(default='검침', max_length=100, verbose_name='처리현황'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='author',
            field=models.CharField(default='원격검침', max_length=100, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='검침담당'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='dong',
            field=models.CharField(max_length=100, null=True, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='ho',
            field=models.CharField(max_length=100, null=True, verbose_name='호'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='manager',
            field=models.CharField(max_length=100, null=True, verbose_name='관리담당'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='serial',
            field=models.CharField(max_length=100, null=True, verbose_name='기기번호'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='utility',
            field=models.CharField(default='수도', max_length=100, verbose_name='종류'),
        ),
    ]
