# Generated by Django 3.0.6 on 2020-06-29 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('metergram', '0008_auto_20200620_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smeter',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 848286, tzinfo=utc), verbose_name='검침일자'),
        ),
    ]
