# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('metergram', '0009_auto_20200629_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='utility',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='utility',
        ),
        migrations.AddField(
            model_name='meter',
            name='elec',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='전기검침'),
        ),
        migrations.AddField(
            model_name='meter',
            name='water',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수도검침'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='elec',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='전기점검'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='water',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='수도점검'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='검침담당'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='cor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스보정검침'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='dong',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='ho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='호'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리담당'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='mtr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스미터검침'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='cor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스보정검침'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 898215, tzinfo=utc), verbose_name='검침일자'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='mtr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스미터검침'),
        ),
    ]
