# Generated by Django 3.0.6 on 2020-11-15 23:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('metergram', '0015_auto_20200701_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='action',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='dong',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='ho',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='action',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='dong',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='ho',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='manager',
        ),
        migrations.AddField(
            model_name='meter',
            name='actalarm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='경보조치요청'),
        ),
        migrations.AddField(
            model_name='meter',
            name='actgas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스조치요청'),
        ),
        migrations.AddField(
            model_name='meter',
            name='alarm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='경보내용'),
        ),
        migrations.AddField(
            model_name='meter',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='일시'),
        ),
        migrations.AddField(
            model_name='meter',
            name='humidity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='습도(%)'),
        ),
        migrations.AddField(
            model_name='meter',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='세부주소'),
        ),
        migrations.AddField(
            model_name='meter',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='참고사항'),
        ),
        migrations.AddField(
            model_name='meter',
            name='serial',
            field=models.CharField(default=12345678, max_length=100, verbose_name='장치번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meter',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='장치종류'),
        ),
        migrations.AddField(
            model_name='meter',
            name='temp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='온도(*C'),
        ),
        migrations.AddField(
            model_name='meter',
            name='usegas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스상태'),
        ),
        migrations.AddField(
            model_name='meter',
            name='usewater',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='수도상태'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='actalarm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='경보조치요청'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='actgas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스조치요청'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='alarm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='경보내용'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='일시'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='humidity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='습도(%)'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='세부주소'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='참고사항'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='serial',
            field=models.CharField(default='12345678', max_length=100, verbose_name='장치번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smeter',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='장치종류'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='temp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='온도(*C'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='usegas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스상태'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='usewater',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='수도상태'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='일시'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_meters', to='auth.Group', verbose_name='단지명/시군구'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='일시'),
        ),
        migrations.AlterField(
            model_name='smeter',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='단지명/시군구'),
        ),
    ]
