# Generated by Django 3.0.6 on 2020-12-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metergram', '0016_auto_20201116_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='cor',
            new_name='acccor',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='mtr',
            new_name='accmtr',
        ),
        migrations.RenameField(
            model_name='smeter',
            old_name='cor',
            new_name='acccor',
        ),
        migrations.RenameField(
            model_name='smeter',
            old_name='mtr',
            new_name='accmtr',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='actalarm',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='actgas',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='elec',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='usegas',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='usewater',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='water',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='actalarm',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='actgas',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='elec',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='usegas',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='usewater',
        ),
        migrations.RemoveField(
            model_name='smeter',
            name='water',
        ),
        migrations.AddField(
            model_name='meter',
            name='amtmoncor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스보정사용액'),
        ),
        migrations.AddField(
            model_name='meter',
            name='amtmonmtr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스미터사용액'),
        ),
        migrations.AddField(
            model_name='meter',
            name='gasalarm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스알림'),
        ),
        migrations.AddField(
            model_name='meter',
            name='gasprs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스압력(kPa)'),
        ),
        migrations.AddField(
            model_name='meter',
            name='gastmp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스온도(*C)'),
        ),
        migrations.AddField(
            model_name='meter',
            name='homealarm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='집안알림'),
        ),
        migrations.AddField(
            model_name='meter',
            name='homehumid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='집안습도(%)'),
        ),
        migrations.AddField(
            model_name='meter',
            name='hometmp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='집안온도(*C)'),
        ),
        migrations.AddField(
            model_name='meter',
            name='moncor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스보정사용량'),
        ),
        migrations.AddField(
            model_name='meter',
            name='monmtr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스미터사용량'),
        ),
        migrations.AddField(
            model_name='meter',
            name='valveaction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스밸브조작'),
        ),
        migrations.AddField(
            model_name='meter',
            name='valvestatus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스밸브상태'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='amtmoncor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스보정사용액'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='amtmonmtr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스미터사용액'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='gasalarm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스알림'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='gasprs',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스압력(kPa)'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='gastmp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스온도(*C)'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='homealarm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='집안알림'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='homehumid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='집안습도(%)'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='hometmp',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='집안온도(*C)'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='moncor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스보정사용량'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='monmtr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='가스미터사용량'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='valveaction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스밸브조작'),
        ),
        migrations.AddField(
            model_name='smeter',
            name='valvestatus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='가스밸브상태'),
        ),
    ]
