# Generated by Django 3.0.6 on 2020-12-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metergram', '0018_auto_20201210_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='mk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MK'),
        ),
    ]
