# Generated by Django 3.0.6 on 2020-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
        migrations.AddField(
            model_name='task',
            name='charge',
            field=models.CharField(max_length=50, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.CharField(max_length=50, null=True, verbose_name='소속부서'),
        ),
        migrations.AddField(
            model_name='task',
            name='director',
            field=models.DateTimeField(auto_now=True, verbose_name='승인자'),
        ),
        migrations.AddField(
            model_name='task',
            name='manager',
            field=models.CharField(max_length=50, null=True, verbose_name='관리자'),
        ),
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(default='tasks/aptgram.jpg', null=True, upload_to='tasks/%Y/%m/%d', verbose_name='참고'),
        ),
        migrations.AddField(
            model_name='task',
            name='response',
            field=models.CharField(default='관리자 또는 승인자 입력', max_length=200, null=True, verbose_name='업무평가'),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(max_length=50, null=True, verbose_name='담당업무'),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.TextField(max_length=500, null=True, verbose_name='업무내역'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일자'),
        ),
    ]
