# Generated by Django 3.0.6 on 2020-06-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgram', '0002_auto_20200606_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='관리일자'),
        ),
        migrations.AlterField(
            model_name='task',
            name='director',
            field=models.CharField(max_length=50, null=True, verbose_name='승인자'),
        ),
    ]
