# Generated by Django 3.0.6 on 2020-06-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgram', '0005_auto_20200615_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='소속부서'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='승인역'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='manager',
            field=models.CharField(max_length=100, null=True, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='담당업무'),
        ),
        migrations.AlterField(
            model_name='task',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='소속부서'),
        ),
        migrations.AlterField(
            model_name='task',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='승인역'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.CharField(max_length=100, null=True, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='담당업무'),
        ),
    ]
