# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskgram', '0007_auto_20200629_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 2, 42, 39, 870289, tzinfo=utc), null=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='관리소장'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='지시사항'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 2, 42, 39, 870289, tzinfo=utc), null=True, verbose_name='관리일자'),
        ),
        migrations.AlterField(
            model_name='task',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소속부서'),
        ),
        migrations.AlterField(
            model_name='task',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리소장'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리자'),
        ),
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, default='tasks/aptgram.jpg', null=True, upload_to='tasks/%Y/%m/%d', verbose_name='참고'),
        ),
        migrations.AlterField(
            model_name='task',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='지시사항'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당업무'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='업무내역'),
        ),
    ]
