# Generated by Django 3.0.6 on 2020-06-30 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskgram', '0010_auto_20200630_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='작성일자'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='관리일자'),
        ),
    ]
