# Generated by Django 3.0.6 on 2020-07-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgram', '0011_auto_20200630_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(default='필수', max_length=100, verbose_name='소속부서'),
        ),
    ]
