# Generated by Django 3.0.6 on 2020-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgram', '0012_auto_20200701_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='결재'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='업무내용'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='결재일자'),
        ),
    ]
