# Generated by Django 3.0.6 on 2020-12-10 08:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('taskgram', '0013_auto_20200911_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask',
            name='charge',
            field=models.CharField(max_length=100, null=True, verbose_name='담당'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='확인'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='사용목적'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='manager',
            field=models.CharField(max_length=100, null=True, verbose_name='관리'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='추가사항'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='task',
            field=models.TextField(max_length=500, null=True, verbose_name='기록내용'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='수정일자'),
        ),
        migrations.AlterField(
            model_name='task',
            name='charge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='담당'),
        ),
        migrations.AlterField(
            model_name='task',
            name='department',
            field=models.CharField(max_length=100, verbose_name='소속'),
        ),
        migrations.AlterField(
            model_name='task',
            name='director',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='확인'),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tasks', to='auth.Group', verbose_name='사용목적'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='관리'),
        ),
        migrations.AlterField(
            model_name='task',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='추가사항'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='기록내용'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일자'),
        ),
    ]
