# Generated by Django 3.0.6 on 2020-09-23 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='작성자')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='아파트명')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='투표:선거')),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='공개일자')),
                ('open_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='개시일시')),
                ('close_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='마감일시')),
                ('remark', models.CharField(max_length=200, verbose_name='비고')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='작성일자')),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='정정일자')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='투표:선거')),
                ('pub_date', models.DateTimeField(verbose_name='공개일자')),
                ('open_date', models.DateTimeField(verbose_name='개시일시')),
                ('close_date', models.DateTimeField(verbose_name='마감일시')),
                ('remark', models.CharField(max_length=200, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='정정일자')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_polls', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_polls', to='auth.Group', verbose_name='아파트명')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=200, verbose_name='비고')),
                ('votes', models.IntegerField(default=0, verbose_name='투표수')),
                ('remark', models.CharField(max_length=200, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성일자')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='정정일자')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollgram.Poll', verbose_name='투표:선거')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
