# Generated by Django 3.0.6 on 2020-07-23 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ssusun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='원격검침', max_length=100, verbose_name='작성자')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='아파트명')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='대분류')),
                ('subject', models.CharField(default='대상', max_length=100, verbose_name='대상')),
                ('treatment', models.CharField(blank=True, max_length=100, null=True, verbose_name='공사종별')),
                ('method', models.CharField(blank=True, max_length=100, null=True, verbose_name='공사방법')),
                ('cycle', models.IntegerField(blank=True, default=0, null=True, verbose_name='수선주기(년)')),
                ('ratio', models.IntegerField(blank=True, default=0, null=True, verbose_name='수선율(%)')),
                ('last', models.IntegerField(blank=True, default=0, null=True, verbose_name='최종수선(년)')),
                ('rule', models.IntegerField(blank=True, default=0, null=True, verbose_name='법정예정(년)')),
                ('plan', models.IntegerField(blank=True, default=0, null=True, verbose_name='최종예정(년)')),
                ('cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='수선예정금(원)')),
                ('times', models.IntegerField(blank=True, default=0, null=True, verbose_name='수선예정회수')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='총수선예정금액')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='최초기안일자')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='최근수정일자')),
            ],
            options={
                'ordering': ['-category', '-subject'],
            },
        ),
        migrations.CreateModel(
            name='Susun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='대분류')),
                ('subject', models.CharField(default='대상', max_length=100, verbose_name='대상')),
                ('treatment', models.CharField(blank=True, max_length=100, null=True, verbose_name='공사종별')),
                ('method', models.CharField(blank=True, max_length=100, null=True, verbose_name='공사방법')),
                ('cycle', models.IntegerField(blank=True, default=0, null=True, verbose_name='수선주기(년)')),
                ('ratio', models.IntegerField(blank=True, default=0, null=True, verbose_name='수선율(%)')),
                ('last', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='최종수선(년)')),
                ('rule', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='법정예정(년)')),
                ('plan', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='최종예정(년)')),
                ('cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='수선예정금(원)')),
                ('times', models.IntegerField(blank=True, default=0, null=True, verbose_name='수선예정회수')),
                ('amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='총수선예정금액')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='최초기안일자')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='최근수정일자')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_susuns', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_susuns', to='auth.Group', verbose_name='아파트명')),
            ],
            options={
                'ordering': ['-category', '-subject'],
            },
        ),
    ]
