# Generated by Django 3.0.6 on 2020-09-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susungram', '0002_auto_20200823_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='susun',
            name='file',
            field=models.FileField(default='susun/SMK.xlsx', null=True, upload_to='susun/%Y/%m/%d', verbose_name='견적서'),
        ),
    ]
