# Generated by Django 3.0.6 on 2020-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('susungram', '0004_auto_20200908_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssusun',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='총수선예정금액(자동계산)'),
        ),
        migrations.AlterField(
            model_name='susun',
            name='file',
            field=models.FileField(default='susun/aptgram.xlsx', null=True, upload_to='susun/%Y/%m/%d', verbose_name='견적서'),
        ),
    ]
