# Generated by Django 3.0.6 on 2020-06-20 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sjumin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='작성자')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='아파트명')),
                ('dong', models.CharField(max_length=100, null=True, verbose_name='동')),
                ('ho', models.CharField(max_length=100, null=True, verbose_name='호')),
                ('represent', models.CharField(max_length=100, null=True, verbose_name='세대주')),
                ('family', models.CharField(max_length=100, null=True, verbose_name='가족정보')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='대표전화')),
                ('car', models.CharField(max_length=100, null=True, verbose_name='자동차')),
                ('date', models.DateField(null=True, verbose_name='입주일자')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='비고')),
                ('file', models.FileField(default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='첨부자료')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Jumin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dong', models.CharField(max_length=100, null=True, verbose_name='동')),
                ('ho', models.CharField(max_length=100, null=True, verbose_name='호')),
                ('represent', models.CharField(max_length=100, null=True, verbose_name='세대주')),
                ('family', models.CharField(max_length=100, null=True, verbose_name='가족정보')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='대표전화')),
                ('car', models.CharField(max_length=100, null=True, verbose_name='자동차')),
                ('date', models.DateField(blank=True, null=True, verbose_name='입주일자')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='비고')),
                ('file', models.FileField(default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='첨부자료')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jumins', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_jumins', to='auth.Group', verbose_name='아파트명')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
