# Generated by Django 3.0.6 on 2020-06-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumin',
            name='date',
            field=models.DateField(blank=True, default='2020-06-28', verbose_name='입주일자'),
        ),
    ]
