# Generated by Django 3.0.6 on 2020-06-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumin',
            name='file',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='text',
        ),
        migrations.AddField(
            model_name='jumin',
            name='charge',
            field=models.CharField(max_length=50, null=True, verbose_name='처리담당'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='department',
            field=models.CharField(max_length=50, null=True, verbose_name='처리부서'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='photo_1',
            field=models.ImageField(default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='민원사진'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='photo_2',
            field=models.ImageField(default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='처리사진'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='subject',
            field=models.CharField(max_length=50, null=True, verbose_name='민원제목'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='task_1',
            field=models.TextField(max_length=500, null=True, verbose_name='민원내역'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='task_2',
            field=models.TextField(max_length=500, null=True, verbose_name='처리내역'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='민원제기일자'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='응답&처리일자'),
        ),
    ]
