# Generated by Django 3.0.6 on 2020-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0002_auto_20200606_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumin',
            name='response',
            field=models.CharField(default='처리결과에 대한 평가', max_length=50, null=True, verbose_name='민원평가'),
        ),
    ]
