# Generated by Django 3.0.6 on 2020-06-29 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0002_auto_20200628_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumin',
            name='date',
            field=models.DateField(blank=True, default='2020-06-29', verbose_name='입주일자'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 811416, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 29, 5, 25, 43, 812409, tzinfo=utc)),
        ),
    ]
