# Generated by Django 3.0.6 on 2020-06-30 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0003_auto_20200629_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumin',
            name='car',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='자동차'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='date',
            field=models.DateField(blank=True, default='2020-06-30', verbose_name='입주일자'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='dong',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='family',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='가족정보'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='file',
            field=models.FileField(blank=True, default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='입주자카드'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='ho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='호'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='대표전화'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='represent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='세대주'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 862282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='family',
            field=models.CharField(max_length=200, null=True, verbose_name='가족정보'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 2, 42, 39, 862282, tzinfo=utc)),
        ),
    ]
