# Generated by Django 3.0.6 on 2020-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0003_jumin_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumin',
            name='contact',
            field=models.CharField(default='신청인의 주소와 연락처 기재란', max_length=10, verbose_name='신청인'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='response',
            field=models.CharField(default='처리결과에 대한 평가', max_length=200, verbose_name='민원평가'),
        ),
    ]
