# Generated by Django 3.0.6 on 2020-06-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0004_auto_20200606_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumin',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='response',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='task_1',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='task_2',
        ),
        migrations.AddField(
            model_name='jumin',
            name='car',
            field=models.CharField(max_length=100, null=True, verbose_name='자동차'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='date',
            field=models.DateField(null=True, verbose_name='입주일자'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='dong',
            field=models.CharField(max_length=10, null=True, verbose_name='동'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='family',
            field=models.CharField(max_length=100, null=True, verbose_name='가족정보'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='file',
            field=models.FileField(default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='첨부자료'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='ho',
            field=models.CharField(max_length=10, null=True, verbose_name='호'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='대표전화'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='remark',
            field=models.CharField(max_length=100, null=True, verbose_name='비고'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='represent',
            field=models.CharField(max_length=20, null=True, verbose_name='세대주'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
