# Generated by Django 3.0.6 on 2020-06-30 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0004_auto_20200630_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sjumin',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 6, 48, 32, 617877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 30, 6, 48, 32, 617877, tzinfo=utc)),
        ),
    ]
