# Generated by Django 3.0.6 on 2020-06-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0005_auto_20200610_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sjumin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, null=True, verbose_name='작성자')),
                ('dong', models.CharField(max_length=10, null=True, verbose_name='동')),
                ('ho', models.CharField(max_length=10, null=True, verbose_name='호')),
                ('represent', models.CharField(max_length=20, null=True, verbose_name='세대주')),
                ('family', models.CharField(max_length=100, null=True, verbose_name='가족정보')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='대표전화')),
                ('car', models.CharField(max_length=100, null=True, verbose_name='자동차')),
                ('date', models.DateField(null=True, verbose_name='입주일자')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='비고')),
                ('file', models.FileField(default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='첨부자료')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
