# Generated by Django 3.0.6 on 2020-06-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0006_sjumin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumin',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='입주일자'),
        ),
    ]
