# Generated by Django 3.0.6 on 2020-07-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0007_auto_20200630_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumin',
            name='photo',
            field=models.ImageField(blank=True, default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='알림 사진'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='task_apt',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='전체 알림'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='task_dong',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='동별 알림'),
        ),
        migrations.AddField(
            model_name='jumin',
            name='task_ho',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='개별 알림'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='file',
            field=models.FileField(blank=True, default='jumins/aptgram.jpg', null=True, upload_to='jumins/%Y/%m/%d', verbose_name='알림 파일'),
        ),
    ]
