# Generated by Django 3.0.6 on 2020-07-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0008_auto_20200707_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sjumin',
            name='file',
        ),
        migrations.AlterField(
            model_name='jumin',
            name='dong',
            field=models.CharField(max_length=100, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='ho',
            field=models.CharField(max_length=100, verbose_name='호'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='task_apt',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='전체 알림'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='task_dong',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='동별 알림'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='task_ho',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='개별 알림'),
        ),
    ]
