# Generated by Django 3.0.6 on 2020-06-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('jumingram', '0008_jumin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='sjumin',
            name='group',
            field=models.CharField(max_length=30, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_jumins', to='auth.Group', verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='author',
            field=models.CharField(max_length=30, null=True, verbose_name='작성자'),
        ),
    ]
