# Generated by Django 3.0.6 on 2020-06-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0009_auto_20200615_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumin',
            name='dong',
            field=models.CharField(max_length=100, null=True, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='ho',
            field=models.CharField(max_length=100, null=True, verbose_name='호'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='대표전화'),
        ),
        migrations.AlterField(
            model_name='jumin',
            name='represent',
            field=models.CharField(max_length=100, null=True, verbose_name='세대주'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='dong',
            field=models.CharField(max_length=100, null=True, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='아파트명'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='ho',
            field=models.CharField(max_length=100, null=True, verbose_name='호'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='대표전화'),
        ),
        migrations.AlterField(
            model_name='sjumin',
            name='represent',
            field=models.CharField(max_length=100, null=True, verbose_name='세대주'),
        ),
    ]
