# Generated by Django 3.0.6 on 2020-08-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0011_auto_20200723_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumin',
            name='file',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='task_apt',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='task_dong',
        ),
        migrations.RemoveField(
            model_name='jumin',
            name='task_ho',
        ),
    ]
