# Generated by Django 3.0.6 on 2020-09-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jumingram', '0013_auto_20200911_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumin',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='투표권'),
        ),
        migrations.AddField(
            model_name='sjumin',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='투표권'),
        ),
    ]
